### ISSUE TITLE
Make work with HyperlinkedModelSerializer 

### ISSUE THREAD

**Issue by andersondborges** [ydaniv/django-rest-assured#11]
should validate hyperlink in _update_check_db not just id to ForeignKey

**Comment by ydaniv** [comment]
As the name implies, `_update_check_db()` checks the instance in the DB. The hyperlink created dynamically by django/DRF and is not stored in DB, or perhaps I don't fully understand your request?

Besides that, you're free to override anything and check additional properties as you like.

**Comment by andersondborges** [comment]
You right, the _update_check_db check for  instance in the DB, but when the the is a  ForeignKey on the serialiazer and the this ForeignKey is a HyperlinkedModelSerializer, the serielizer expect a URL to this foreignkey not the id.

ex:
assertEqual(attribute, results.get(key, value))
AssertionError: u'470' != u'/api/v1/my-url/470/'

in the instance db the foreignkey is a id but in the results the foreignkey on the serielizer is a URL.

http://www.django-rest-framework.org/api-guide/serializers/#hyperlinkedmodelserializer

**Comment by ydaniv** [comment]
aha, I see. excellent point! Thanks!

basically you can override to transform the expected result into a url
using `reverse ()`, but I'll see if its possible to do some introspection
and automatically check for a url instead.
בתאריך 7 במאי 2015 21:30,‏ "andersondborges" <notifications@github.com> כתב:

**Comment by ydaniv** [comment]
Fixed now in master. Working now on release 0.2.0, once it's done it'll be in pypi.
see: https://github.com/ydaniv/django-rest-assured/commit/6840d1463964123282f4c84f51b2b25c73fe3bb4
