### ISSUE TITLE
DRF 3.3 support when it is released

### ISSUE THREAD

**Issue by auvipy** [ydaniv/django-rest-assured#16]

**Comment by ydaniv** [comment]
Sure, as soon as #13 is resolved.

**Comment by ydaniv** [comment]
tests pass but currently I'm still using 3.1 myself, so feel free to open specific issues if anything pops up.
Thanks!

**Comment by auvipy** [comment]
that means it;s supported!!! ok test my self and report issue if anything rises

**Comment by ydaniv** [comment]
:+1:
