### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by ydaniv** [ydaniv/django-rest-assured#17]
Currently tests fail pretty badly on errors from DB.
I'm pretty much clueless of their origin.

**Comment by yprez** [comment]
There is something broken with the tests.
Using pytest-django reduces some clutter and fixes the tests on Django 1.9...

I'm still trying to figure out how to make this work for all versions of Python/Django/DRF, 90% done.

**Comment by ydaniv** [comment]
:+1: :star2: :+1:

**Comment by yprez** [comment]
@ydaniv can be closed via #19
woop!

**Comment by ydaniv** [comment]
wOOt! indeed closed via #19 
Thanks @yprez!
