### ISSUE TITLE
working with model_mummy

### ISSUE THREAD

**Issue by auvipy** [ydaniv/django-rest-assured#25]
any way to use with model_mummy instead of factory boy?

**Comment by ydaniv** [comment]
basically yes, the API is agnostic to object factory. It only depends on Django and DRF.

**Comment by auvipy** [comment]
ohh great to know :D 

should I just replace model factory with model_mummy?

**Comment by ydaniv** [comment]
well... not that easy. OOTB it uses factory-boy's API. If you want to use model mommy you'll need to override `get_object()` to get the object from the factory class.

So, from quickly going over the docs, I assume it'll be something like:

```
def get_object(factory):
    return mommy.make(factory)
```

**Comment by auvipy** [comment]
OK thank you

**Comment by ydaniv** [comment]
@auvipy did my suggestion do the trick? Can I close this one?
