### ISSUE TITLE
pinned requirements

### ISSUE THREAD

**Issue by eracle** [ydaniv/django-rest-assured#36]
Hello there!
I will start trying to use the project today: it seems interesting. 
One question, why aren't the requirements pinned?
Thanks! Hope to contribute here soon.

**Comment by ydaniv** [comment]
Hi @eracle,
Please, be my guest!

Requirements are pinned in `setup.py`, and probably in your project, so I doubt if pinning the in `requirements.txt` is also necessary.

But if it really concerns you, you could send a PR with the versions in `setup.py` copied to `requirements.txt` and it could count as a first contribution (:
