### ISSUE TITLE
Licence: is not open source

### ISSUE THREAD

**Issue by eracle** [ydaniv/django-rest-assured#38]
There BSD in the readme file, then when you take a look on the Licence file, there is no mention of it.
Sorry, I've just seen this and I changed my mind, I will not collaborate here!

**Comment by ydaniv** [comment]
If you actually _read_ the `LICENSE` you'll see that it _is_ a BSD 2-clause license. It doesn't need to mention it, it's just written there.
Good day to you too

**Comment by eracle** [comment]
I am really sorry, I've got it wrong.
I hope you accept my apologies.

**Comment by ydaniv** [comment]
sure, np
